Include all tripleo-common* packages from current dlrn
openstack-tripleo-common now depends on
openstack-tripleo-common-containers. If this package is not explicitly
included in the packages from the 'current' repo, undercloud updates
fail with an error similar to:

Error: Package: openstack-tripleo-common-7.0.1-0.zzz.el7.centos.noarch (delorean-current)
           Requires: openstack-tripleo-common-containers = 7.0.1-0.zzz.el7.centos

Change-Id: I5c112dc7f5530e246ce66f7491c604930290ff2f